/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.homebeaver.aismodel;

import java.io.IOException;
//import org.openapitools.client.model.AssignedModeCommandCommands0;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * AssignedModeCommandCommands
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class AssignedModeCommandCommands {
  public static final String SERIALIZED_NAME_0 = "0";
  @SerializedName(SERIALIZED_NAME_0)
  private AssignedModeCommandCommands0 _0;

  public static final String SERIALIZED_NAME_1 = "1";
  @SerializedName(SERIALIZED_NAME_1)
  private AssignedModeCommandCommands0 _1;

  public AssignedModeCommandCommands() { 
  }

  public AssignedModeCommandCommands _0(AssignedModeCommandCommands0 _0) {
    this._0 = _0;
    return this;
  }

   /**
   * Get _0
   * @return _0
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public AssignedModeCommandCommands0 get0() {
    return _0;
  }


  public void set0(AssignedModeCommandCommands0 _0) {
    this._0 = _0;
  }


  public AssignedModeCommandCommands _1(AssignedModeCommandCommands0 _1) {
    this._1 = _1;
    return this;
  }

   /**
   * Get _1
   * @return _1
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public AssignedModeCommandCommands0 get1() {
    return _1;
  }


  public void set1(AssignedModeCommandCommands0 _1) {
    this._1 = _1;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedModeCommandCommands assignedModeCommandCommands = (AssignedModeCommandCommands) o;
    return Objects.equals(this._0, assignedModeCommandCommands._0) &&
        Objects.equals(this._1, assignedModeCommandCommands._1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_0, _1);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignedModeCommandCommands {\n");
    sb.append("    _0: ").append(toIndentedString(_0)).append("\n");
    sb.append("    _1: ").append(toIndentedString(_1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("0");
    openapiFields.add("1");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("0");
    openapiRequiredFields.add("1");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AssignedModeCommandCommands
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AssignedModeCommandCommands.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AssignedModeCommandCommands is not found in the empty JSON string", AssignedModeCommandCommands.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AssignedModeCommandCommands.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AssignedModeCommandCommands` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AssignedModeCommandCommands.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `0`
      if (jsonObj.getAsJsonObject("0") != null) {
        AssignedModeCommandCommands0.validateJsonObject(jsonObj.getAsJsonObject("0"));
      }
      // validate the optional field `1`
      if (jsonObj.getAsJsonObject("1") != null) {
        AssignedModeCommandCommands0.validateJsonObject(jsonObj.getAsJsonObject("1"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AssignedModeCommandCommands.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AssignedModeCommandCommands' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AssignedModeCommandCommands> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AssignedModeCommandCommands.class));

       return (TypeAdapter<T>) new TypeAdapter<AssignedModeCommandCommands>() {
           @Override
           public void write(JsonWriter out, AssignedModeCommandCommands value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AssignedModeCommandCommands read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

	public static AssignedModeCommandCommands fromJson(JSONObject jo) {
		AssignedModeCommandCommands res = new AssignedModeCommandCommands();
		// Extract individual fields from JSONObject
		try {
			JSONObject _0 = jo.getJSONObject(SERIALIZED_NAME_0);
			JSONObject _1 = jo.getJSONObject(SERIALIZED_NAME_1);
			res = res._0(AssignedModeCommandCommands0.fromJson(_0))
			._1(AssignedModeCommandCommands0.fromJson(_1));
		} catch (JSONException e) {
//	    	logger.error("Error creating AssignedModeCommandCommands", e);
			System.out.println("Error creating AssignedModeCommandCommands " + e);
		}
		return res;
	}

}

