/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.homebeaver.aismodel;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * BinaryBroadcastMessage Message ID 8
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class BinaryBroadcastMessage extends AisMessage {

  public static final String SERIALIZED_NAME_SPARE = "Spare";
  @SerializedName(SERIALIZED_NAME_SPARE)
  private Integer spare;

  public static final String SERIALIZED_NAME_APPLICATION_I_D = "ApplicationID";
  @SerializedName(SERIALIZED_NAME_APPLICATION_I_D)
  private AddressedBinaryMessageApplicationID applicationID;

  public static final String SERIALIZED_NAME_BINARY_DATA = "BinaryData";
  @SerializedName(SERIALIZED_NAME_BINARY_DATA)
  private String binaryData;

	public BinaryBroadcastMessage() {
		super();
	}

  public BinaryBroadcastMessage spare(Integer spare) {
    this.spare = spare;
    return this;
  }

   /**
   * Get spare
   * @return spare
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSpare() {
    return spare;
  }


  public void setSpare(Integer spare) {
    this.spare = spare;
  }


  public BinaryBroadcastMessage applicationID(AddressedBinaryMessageApplicationID applicationID) {
    
    this.applicationID = applicationID;
    return this;
  }

   /**
   * Get applicationID
   * @return applicationID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public AddressedBinaryMessageApplicationID getApplicationID() {
    return applicationID;
  }


  public void setApplicationID(AddressedBinaryMessageApplicationID applicationID) {
    this.applicationID = applicationID;
  }


  public BinaryBroadcastMessage binaryData(String binaryData) {
    
    this.binaryData = binaryData;
    return this;
  }

   /**
   * Get binaryData
   * @return binaryData
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBinaryData() {
    return binaryData;
  }


  public void setBinaryData(String binaryData) {
    this.binaryData = binaryData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryBroadcastMessage binaryBroadcastMessage = (BinaryBroadcastMessage) o;
    return Objects.equals(getMessageID(), binaryBroadcastMessage.getMessageID()) &&
            Objects.equals(getRepeatIndicator(), binaryBroadcastMessage.getRepeatIndicator()) &&
            Objects.equals(getUserID(), binaryBroadcastMessage.getUserID()) &&
            Objects.equals(getValid(), binaryBroadcastMessage.getValid()) &&
        Objects.equals(this.spare, binaryBroadcastMessage.spare) &&
        Objects.equals(this.applicationID, binaryBroadcastMessage.applicationID) &&
        Objects.equals(this.binaryData, binaryBroadcastMessage.binaryData);
  }

  @Override
  public int hashCode() {
	return Objects.hash(getMessageID(), getRepeatIndicator(), getUserID(), getValid(), 
	spare, applicationID, binaryData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryBroadcastMessage {\n");
    sb.append("    messageID: ").append(toIndentedString(getMessageID())).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(getRepeatIndicator())).append("\n");
    sb.append("    userID: ").append(toIndentedString(getUserID())).append("\n");
    sb.append("    valid: ").append(toIndentedString(getValid())).append("\n");
    sb.append("    spare: ").append(toIndentedString(spare)).append("\n");
    sb.append("    applicationID: ").append(toIndentedString(applicationID)).append("\n");
    sb.append("    binaryData: ").append(toIndentedString(binaryData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("Spare");
    openapiFields.add("ApplicationID");
    openapiFields.add("BinaryData");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("Spare");
    openapiRequiredFields.add("ApplicationID");
    openapiRequiredFields.add("BinaryData");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BinaryBroadcastMessage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BinaryBroadcastMessage.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BinaryBroadcastMessage is not found in the empty JSON string", BinaryBroadcastMessage.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BinaryBroadcastMessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BinaryBroadcastMessage` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BinaryBroadcastMessage.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `ApplicationID`
      if (jsonObj.getAsJsonObject("ApplicationID") != null) {
        AddressedBinaryMessageApplicationID.validateJsonObject(jsonObj.getAsJsonObject("ApplicationID"));
      }
      if (jsonObj.get("BinaryData") != null && !jsonObj.get("BinaryData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BinaryData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BinaryData").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BinaryBroadcastMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BinaryBroadcastMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BinaryBroadcastMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BinaryBroadcastMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<BinaryBroadcastMessage>() {
           @Override
           public void write(JsonWriter out, BinaryBroadcastMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BinaryBroadcastMessage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

	public static BinaryBroadcastMessage fromJson(JSONObject jo) {
		AisMessage res = new BinaryBroadcastMessage();
		BinaryBroadcastMessage msg = null;
		// Extract individual fields from JSONObject
		try {
			res = res.messageID(jo.getInt(SERIALIZED_NAME_MESSAGE_I_D));
			res = res.repeatIndicator(jo.getInt(SERIALIZED_NAME_REPEAT_INDICATOR));
			res = res.userID(jo.getInt(SERIALIZED_NAME_USER_I_D));
			res = res.valid(jo.getBoolean(SERIALIZED_NAME_VALID));
			msg = (BinaryBroadcastMessage) res;
			msg = msg.spare(jo.getInt(SERIALIZED_NAME_SPARE));
			JSONObject data = jo.getJSONObject(SERIALIZED_NAME_APPLICATION_I_D);
			msg = msg.applicationID(AddressedBinaryMessageApplicationID.fromJson(data));
			msg = msg.binaryData(jo.getString(SERIALIZED_NAME_BINARY_DATA));
			System.out.println(msg);
		} catch (JSONException e) {
//			logger.error("Error creating BinaryBroadcastMessage", e);
			System.out.println("Error creating BinaryBroadcastMessage " + e);
		}
		return msg;
	}

}

