/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.homebeaver.aismodel;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * BinaryAcknowledge Message ID 7
 * <p>
 * Message 7 should be used as an acknowledgement of up to four Message 6 (ADDRESSEDBINARYMESSAGE) messages 
 * received (see § 5.3.1, Annex 2) and should be transmitted on the channel, 
 * where the addressed message to be acknowledged was received.
 * <p>
 * Message 13 should be used as an acknowledgement of up to four Message 12 (ADDRESSEDSAFETYMESSAGE) messages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class BinaryAcknowledge extends AisMessage {

  public static final String SERIALIZED_NAME_SPARE = "Spare";
  @SerializedName(SERIALIZED_NAME_SPARE)
  private Integer spare;

  public static final String SERIALIZED_NAME_DESTINATIONS = "Destinations";
  @SerializedName(SERIALIZED_NAME_DESTINATIONS)
  private BinaryAcknowledgeDestinations destinations;

	public BinaryAcknowledge() {
		super();
	}

  public BinaryAcknowledge spare(Integer spare) {
    this.spare = spare;
    return this;
  }

   /**
   * Get spare
   * @return spare
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSpare() {
    return spare;
  }


  public void setSpare(Integer spare) {
    this.spare = spare;
  }


  public BinaryAcknowledge destinations(BinaryAcknowledgeDestinations destinations) {
    
    this.destinations = destinations;
    return this;
  }

   /**
   * Get destinations
   * @return destinations
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BinaryAcknowledgeDestinations getDestinations() {
    return destinations;
  }

  public void setDestinations(BinaryAcknowledgeDestinations destinations) {
    this.destinations = destinations;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryAcknowledge binaryAcknowledge = (BinaryAcknowledge) o;
    return Objects.equals(getMessageID(), binaryAcknowledge.getMessageID()) &&
           Objects.equals(getRepeatIndicator(), binaryAcknowledge.getRepeatIndicator()) &&
           Objects.equals(getUserID(), binaryAcknowledge.getUserID()) &&
           Objects.equals(getValid(), binaryAcknowledge.getValid()) &&
        Objects.equals(this.spare, binaryAcknowledge.spare) &&
        Objects.equals(this.destinations, binaryAcknowledge.destinations);
  }

  @Override
  public int hashCode() {
	return Objects.hash(getMessageID(), getRepeatIndicator(), getUserID(), getValid(), 
    spare, destinations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryAcknowledge {\n");
    sb.append("    messageID: ").append(toIndentedString(getMessageID())).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(getRepeatIndicator())).append("\n");
    sb.append("    userID: ").append(toIndentedString(getUserID())).append("\n");
    sb.append("    valid: ").append(toIndentedString(getValid())).append("\n");
    sb.append("    spare: ").append(toIndentedString(spare)).append("\n");
    sb.append("    destinations: ").append(toIndentedString(destinations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("Spare");
    openapiFields.add("Destinations");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("Spare");
    openapiRequiredFields.add("Destinations");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BinaryAcknowledge
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BinaryAcknowledge.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BinaryAcknowledge is not found in the empty JSON string", BinaryAcknowledge.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BinaryAcknowledge.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BinaryAcknowledge` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BinaryAcknowledge.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `Destinations`
      if (jsonObj.getAsJsonObject("Destinations") != null) {
        BinaryAcknowledgeDestinations.validateJsonObject(jsonObj.getAsJsonObject("Destinations"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BinaryAcknowledge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BinaryAcknowledge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BinaryAcknowledge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BinaryAcknowledge.class));

       return (TypeAdapter<T>) new TypeAdapter<BinaryAcknowledge>() {
           @Override
           public void write(JsonWriter out, BinaryAcknowledge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BinaryAcknowledge read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

/*
{"Message":{"BinaryAcknowledge":{"Destinations":
{"0":{"DestinationID":2770030,"Sequenceinteger":1,"Valid":true}
,"1":{"DestinationID":0,"Sequenceinteger":0,"Valid":false}
,"2":{"DestinationID":0,"Sequenceinteger":0,"Valid":false}
,"3":{"DestinationID":0,"Sequenceinteger":0,"Valid":false}}
,"MessageID":7,"RepeatIndicator":0,"Spare":0,"UserID":354641000,"Valid":true}}
,"MessageType":"BinaryAcknowledge"
,"MetaData":{"MMSI":354641000,"MMSI_String":354641000,"ShipName":"HORIZON GEOBAY      ","latitude":55.683213333333335,"longitude":21.139529999999997,"time_utc":"2025-10-30 19:44:34.2579612 +0000 UTC"}}

 */
	public static BinaryAcknowledge fromJson(JSONObject jo) {
		AisMessage res = new BinaryAcknowledge();
		BinaryAcknowledge msg = null;
		// Extract individual fields from JSONObject
		try {
			res = res.messageID(jo.getInt(SERIALIZED_NAME_MESSAGE_I_D));
			res = res.repeatIndicator(jo.getInt(SERIALIZED_NAME_REPEAT_INDICATOR));
			res = res.userID(jo.getInt(SERIALIZED_NAME_USER_I_D));
			res = res.valid(jo.getBoolean(SERIALIZED_NAME_VALID));
			msg = (BinaryAcknowledge) res;
			msg = msg.spare(jo.getInt(SERIALIZED_NAME_SPARE));
			JSONObject data = jo.getJSONObject(SERIALIZED_NAME_DESTINATIONS);
			msg = msg.destinations(BinaryAcknowledgeDestinations.fromJson(data));
//			System.out.println(msg);
		} catch (JSONException e) {
//			logger.error("Error creating DataLinkManagementMessage", e);
			System.out.println("Error creating DataLinkManagementMessage " + e);
		}
		return msg;
	}

}