/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.homebeaver.aismodel;


import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * DataLinkManagementMessage Message ID 20 Reserve slots for base station(s)
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class DataLinkManagementMessage extends AisMessage {

  public static final String SERIALIZED_NAME_SPARE = "Spare";
  @SerializedName(SERIALIZED_NAME_SPARE)
  private Integer spare;

  public static final String SERIALIZED_NAME_DATA = "Data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private DataLinkManagementMessageData data;

	public DataLinkManagementMessage() {
		super();
	}

	public DataLinkManagementMessage spare(Integer spare) {
		this.spare = spare;
		return this;
	}

   /**
   * Get spare
   * @return spare
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSpare() {
    return spare;
  }

	public void setSpare(Integer spare) {
		this.spare = spare;
	}

	public DataLinkManagementMessage data(DataLinkManagementMessageData data) {
		this.data = data;
		return this;
	}

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public DataLinkManagementMessageData getData() {
    return data;
  }


  public void setData(DataLinkManagementMessageData data) {
    this.data = data;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataLinkManagementMessage dataLinkManagementMessage = (DataLinkManagementMessage) o;
    return Objects.equals(getMessageID(), dataLinkManagementMessage.getMessageID()) &&
           Objects.equals(getRepeatIndicator(), dataLinkManagementMessage.getRepeatIndicator()) &&
           Objects.equals(getUserID(), dataLinkManagementMessage.getUserID()) &&
           Objects.equals(getValid(), dataLinkManagementMessage.getValid()) &&
           Objects.equals(this.spare, dataLinkManagementMessage.spare) &&
           Objects.equals(this.data, dataLinkManagementMessage.data);
  }

  @Override
  public int hashCode() {
	return Objects.hash(getMessageID(), getRepeatIndicator(), getUserID(), getValid(), 
    spare, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataLinkManagementMessage {\n");
    sb.append("    messageID: ").append(toIndentedString(getMessageID())).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(getRepeatIndicator())).append("\n");
    sb.append("    userID: ").append(toIndentedString(getUserID())).append("\n");
    sb.append("    valid: ").append(toIndentedString(getValid())).append("\n");
    sb.append("    spare: ").append(toIndentedString(spare)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("Spare");
    openapiFields.add("Data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("Spare");
    openapiRequiredFields.add("Data");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DataLinkManagementMessage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (DataLinkManagementMessage.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in DataLinkManagementMessage is not found in the empty JSON string", DataLinkManagementMessage.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DataLinkManagementMessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DataLinkManagementMessage` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DataLinkManagementMessage.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `Data`
      if (jsonObj.getAsJsonObject("Data") != null) {
        DataLinkManagementMessageData.validateJsonObject(jsonObj.getAsJsonObject("Data"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DataLinkManagementMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DataLinkManagementMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DataLinkManagementMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DataLinkManagementMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<DataLinkManagementMessage>() {
           @Override
           public void write(JsonWriter out, DataLinkManagementMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DataLinkManagementMessage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

/*
{"Message":{"DataLinkManagementMessage":{"Data":
{"0":{"Increment":750,"Offset":749,"TimeOut":3,"Valid":false,"integerOfSlots":3}
,"1":{"Increment":150,"Offset":789,"TimeOut":3,"Valid":false,"integerOfSlots":5}
,"2":{"Increment":150,"Offset":799,"TimeOut":3,"Valid":false,"integerOfSlots":5}
,"3":{"Increment":150,"Offset":809,"TimeOut":3,"Valid":false,"integerOfSlots":5}}
,"MessageID":20,"RepeatIndicator":3,"Spare":0,"UserID":3669962,"Valid":true}}
,"MessageType":"DataLinkManagementMessage"
,"MetaData":{"MMSI":3669962,"MMSI_String":3669962,"ShipName":"","latitude":44.255833333333335,"longitude":-76.00333333333333,"time_utc":"2025-10-30 20:13:40.500737128 +0000 UTC"}}

 */
	public static DataLinkManagementMessage fromJson(JSONObject jo) {
		AisMessage res = new DataLinkManagementMessage();
		DataLinkManagementMessage msg = null;
		// Extract individual fields from JSONObject
		try {
			res = res.messageID(jo.getInt(SERIALIZED_NAME_MESSAGE_I_D));
			res = res.repeatIndicator(jo.getInt(SERIALIZED_NAME_REPEAT_INDICATOR));
			res = res.userID(jo.getInt(SERIALIZED_NAME_USER_I_D));
			res = res.valid(jo.getBoolean(SERIALIZED_NAME_VALID));
			msg = (DataLinkManagementMessage) res;
			msg = msg.spare(jo.getInt(SERIALIZED_NAME_SPARE));
			JSONObject data = jo.getJSONObject(SERIALIZED_NAME_DATA);
			msg = msg.data(DataLinkManagementMessageData.fromJson(data));
//			System.out.println(msg);
		} catch (JSONException e) {
//			logger.error("Error creating DataLinkManagementMessage", e);
			System.out.println("Error creating DataLinkManagementMessage " + e);
		}
		return msg;
	}

}

