/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.homebeaver.aismodel;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dk.dma.ais.message.NavigationalStatus;
import dk.dma.enav.model.geometry.Position;
import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * PositionReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class PositionReport {
  /* AisMessage1 extends AisPositionMessage
   * or
   * AisMessage2 extends AisMessage1
   * or
   * AisMessage3 extends AisPositionMessage
   * <p>
   * AisMessage3 : Special position report, response to interrogation;(Class A shipborne mobile equipment)
   */
  /**
   * Identifier for this message 1, 2 or 3
   */
  public static final String SERIALIZED_NAME_MESSAGE_I_D = "MessageID";
  private Integer messageID;

  /**
   * Used by the repeater to indicate how many times a message has been repeated. 
   * Refer to ß 4.6.1; 0-3; 
   * 0 = default; 3 = do not repeat any more
   */
  public static final String SERIALIZED_NAME_REPEAT_INDICATOR = "RepeatIndicator";
  @SerializedName(SERIALIZED_NAME_REPEAT_INDICATOR)
  private Integer repeatIndicator;

  /**
   * R-REC-M.1371-1: 3.3.7.2.1 User ID
   * The user ID should be the MMSI. The MMSI is 30 bits long. 
   * The first 9 digits (most significant digits) should be used only. 
   * Recommendation ITU-R M.1083 should not be applied with respect to the 10th digit (least significant digit).
   */
  public static final String SERIALIZED_NAME_USER_I_D = "UserID";
  @SerializedName(SERIALIZED_NAME_USER_I_D)
  private Integer userID;

  public static final String SERIALIZED_NAME_VALID = "Valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  private Boolean valid;

  /**
   * Navigational status: 
   * 0 = under way using engine 
   * 1 = at anchor 
   * 2 = not under command 
   * 3 = restricted manoeuvrability 
   * 4 = constrained by her draught (Tiefgang)
   * 5 = moored (festgemacht)
   * 6 = aground (auf Grund)
   * 7 = engaged in fishing 
   * 8 = under way sailing 
   * 9 = reserved for future amendment of navigational status for ships carrying DG, HS, or MP, or IMO hazard
   * or pollutant category C, high speed craft (HSC), 
   * 10 = reserved for future amendment of navigational status for
   * ships carrying dangerous goods (DG), harmful substances (HS) or marine pollutants (MP), or IMO hazard or
   * pollutant category A, wing in grand (WIG); 
   * 11-13 = reserved for future use 14 = AIS-SART (active) 
   * 15 = not defined = default (also used by AIS-SART under test)
   */
//  protected int navStatus; // 4 bits
  public static final String SERIALIZED_NAME_NAVIGATIONAL_STATUS = "NavigationalStatus";
  @SerializedName(SERIALIZED_NAME_NAVIGATIONAL_STATUS)
  private Integer navigationalStatus;

  /**
   * Rate of Turn (ROT): 
   * 0 to +126 = turning right at up to 708 degrees per min or higher 
   * 0 to -126 = turning left at up to 708 degrees per min or higher 
   * Values between 0 and 708 degrees per min coded by ROTais = 4.733
   * SQRT(ROTsensor) degrees per min where ROTsensor is the Rate of Turn as input by an external Rate of Turn
   * Indicator (TI). ROTais is rounded to the nearest integer value.
   * <p>
   * +127 = turning right at more than 5 degrees per 30 s (No TI available) 
   * -127 = turning left at more than 5 degrees per 30 s (No TI available) 
   * -128 (80 hex) indicates no turn information available (default).
   * <p>
   * ROT data should not be derived from COG information.
   */
//  protected int rot; // 8 bits :
  public static final String SERIALIZED_NAME_RATE_OF_TURN = "RateOfTurn";
  @SerializedName(SERIALIZED_NAME_RATE_OF_TURN)
  private Integer rateOfTurn;

  /**
   * Speed Over Ground Speed over ground in 1/10 knot steps (0-102.2 knots) // 1kn ~ 0,5 m/s
   * 1023 = not available, 
   * 1022 = 102.2 knots or higher
   */
//  protected int sog; // 10 bits
  public static final String SERIALIZED_NAME_SOG = "Sog";
  @SerializedName(SERIALIZED_NAME_SOG)
  private Double sog;

  /**
   * AisPosition Accuracy: The position accuracy (PA) flag should be determined in accordance with Table 47 
   * 1 = high ( =&lt; 10 m) 
   * 0 = low (&gt;10 m) 0 = default
   */
//  protected int posAcc; // 1 bit
  public static final String SERIALIZED_NAME_POSITION_ACCURACY = "PositionAccuracy";
  @SerializedName(SERIALIZED_NAME_POSITION_ACCURACY)
  private Boolean positionAccuracy;

  /**
   * Stores the positions in a general manner
   */
//  protected AisPosition pos; // : Lat/Long 1/10000 minute
  private Position position;
  public static final String SERIALIZED_NAME_LONGITUDE = "Longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private Double longitude;

  public static final String SERIALIZED_NAME_LATITUDE = "Latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private Double latitude;

  /**
   * Course over Ground Course over ground in 1/10 = (0-3599). 
   * 3600 (E10h) = not available = default. 
   * 3601-4095 should not be used
   */
//  protected int cog; // 12 bits
  public static final String SERIALIZED_NAME_COG = "Cog";
  @SerializedName(SERIALIZED_NAME_COG)
  private Double cog;

  /**
   * True heading Degrees (0-359) (511 indicates not available = default)
   */
//  protected int trueHeading; // 9 bits
  public static final String SERIALIZED_NAME_TRUE_HEADING = "TrueHeading";
  @SerializedName(SERIALIZED_NAME_TRUE_HEADING)
  private Integer trueHeading;

  /**
   * Time stamp: UTC second 
   * when the report was generated by the EPFS (
   * 0-59 or 
   * 60 if time stamp is not available, which should also be the default value or 
   * 61 if positioning system is in manual input mode or 
   * 62 if electronic position fixing system operates in estimated (dead reckoning) mode or 
   * 63 if the positioning system is inoperative) 61, 62, 63 are not used by CS AIS
   */
//  protected int utcSec; // 6 bits : UTC Seconds
  public static final String SERIALIZED_NAME_TIMESTAMP = "Timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Integer timestamp;

  /**
   * Special manoeuvre indicator: 
   * 0 = not available = default 
   * 1 = not engaged in special manoeuvre 
   * 2 = engaged in special manoeuvre (i.e.: regional passing arrangement on Inland Waterway)
   * <p>
   * NOTE: This field is added in ITU-R M1371-4
   */
//  protected int specialManIndicator; // 2 bits
  public static final String SERIALIZED_NAME_SPECIAL_MANOEUVRE_INDICATOR = "SpecialManoeuvreIndicator";
  @SerializedName(SERIALIZED_NAME_SPECIAL_MANOEUVRE_INDICATOR)
  private Integer specialManoeuvreIndicator;

  /**
   * Not used. Should be set to zero. Reserved for future use.
   * <p>
   * NOTE: In ITU-R M1371-4 this field is 3 bits compared to 1 previously
   */
//  protected int spare; // 3 bits
  public static final String SERIALIZED_NAME_SPARE = "Spare";
  @SerializedName(SERIALIZED_NAME_SPARE)
  private Integer spare;

  /**
   * RAIM-flag: Receiver autonomous integrity monitoring (RAIM) flag of electronic position fixing device; 
   * 0 = RAIM not in use = default; 
   * 1 = RAIM in use. 
   * See Table 47
   */
//  protected int raim; // 1 bit : RAIM flag
  public static final String SERIALIZED_NAME_RAIM = "Raim";
  @SerializedName(SERIALIZED_NAME_RAIM)
  private Boolean raim;

  /**
   * SOTDMA/ITDMA sync state: sync state is part of the defined communication state (19) bits. The sync state is the
   * first 2 bits of the 19 bits in the communication state of the message.
   * <p>
   * 0 UTC direct (see 3.1.1.1) 1 UTC indirect (see 3.1.1.2) 2 Station is synchronized to a base station (base direct)
   * 3 Station is synchronized to another station based on the highest number of received stations or to another
   * mobile station, which is directly synchronized to a base station
   */
//  protected int syncState; // 2 bits
  public static final String SERIALIZED_NAME_COMMUNICATION_STATE = "CommunicationState";
  @SerializedName(SERIALIZED_NAME_COMMUNICATION_STATE)
  private Integer communicationState;

  public PositionReport() { 
  }

  public PositionReport messageID(Integer messageID) {
    
    this.messageID = messageID;
    return this;
  }

   /**
   * Get messageID
   * @return messageID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getMessageID() {
    return messageID;
  }


  public void setMessageID(Integer messageID) {
    this.messageID = messageID;
  }


  public PositionReport repeatIndicator(Integer repeatIndicator) {
    
    this.repeatIndicator = repeatIndicator;
    return this;
  }

   /**
   * Get repeatIndicator
   * @return repeatIndicator
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getRepeatIndicator() {
    return repeatIndicator;
  }


  public void setRepeatIndicator(Integer repeatIndicator) {
    this.repeatIndicator = repeatIndicator;
  }


  public PositionReport userID(Integer userID) {
    
    this.userID = userID;
    return this;
  }

   /**
   * Get userID
   * @return userID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getUserID() {
    return userID;
  }


  public void setUserID(Integer userID) {
    this.userID = userID;
  }


  public PositionReport valid(Boolean valid) {
    
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getValid() {
    return valid;
  }


  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  public PositionReport navigationalStatus(Integer navigationalStatus) {
    
    this.navigationalStatus = navigationalStatus;
    return this;
  }

   /**
   * Get navigationalStatus
   * @return navigationalStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getNavigationalStatus() {
    return navigationalStatus;
  }


  public void setNavigationalStatus(Integer navigationalStatus) {
    this.navigationalStatus = navigationalStatus;
  }


  public PositionReport rateOfTurn(Integer rateOfTurn) {
    
    this.rateOfTurn = rateOfTurn;
    return this;
  }

   /**
   * Get rateOfTurn
   * @return rateOfTurn
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getRateOfTurn() {
    return rateOfTurn;
  }


  public void setRateOfTurn(Integer rateOfTurn) {
    this.rateOfTurn = rateOfTurn;
  }


  public PositionReport sog(Double sog) {
    
    this.sog = sog;
    return this;
  }

   /**
   * Get sog
   * @return sog
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getSog() {
    return sog;
  }


  public void setSog(Double sog) {
    this.sog = sog;
  }


  public PositionReport positionAccuracy(Boolean positionAccuracy) {
    
    this.positionAccuracy = positionAccuracy;
    return this;
  }

   /**
   * Get positionAccuracy
   * @return positionAccuracy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getPositionAccuracy() {
    return positionAccuracy;
  }


  public void setPositionAccuracy(Boolean positionAccuracy) {
    this.positionAccuracy = positionAccuracy;
  }


  public PositionReport longitude(Double longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getLongitude() {
    return longitude;
  }


  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }


  public PositionReport latitude(Double latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getLatitude() {
    return latitude;
  }


  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }


  public PositionReport cog(Double cog) {
    
    this.cog = cog;
    return this;
  }

   /**
   * Get cog
   * @return cog
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getCog() {
    return cog;
  }


  public void setCog(Double cog) {
    this.cog = cog;
  }


  public PositionReport trueHeading(Integer trueHeading) {
    
    this.trueHeading = trueHeading;
    return this;
  }

   /**
   * Get trueHeading
   * @return trueHeading
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getTrueHeading() {
    return trueHeading;
  }


  public void setTrueHeading(Integer trueHeading) {
    this.trueHeading = trueHeading;
  }


  public PositionReport timestamp(Integer timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  public PositionReport specialManoeuvreIndicator(Integer specialManoeuvreIndicator) {
    
    this.specialManoeuvreIndicator = specialManoeuvreIndicator;
    return this;
  }

   /**
   * Get specialManoeuvreIndicator
   * @return specialManoeuvreIndicator
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSpecialManoeuvreIndicator() {
    return specialManoeuvreIndicator;
  }


  public void setSpecialManoeuvreIndicator(Integer specialManoeuvreIndicator) {
    this.specialManoeuvreIndicator = specialManoeuvreIndicator;
  }


  public PositionReport spare(Integer spare) {
    
    this.spare = spare;
    return this;
  }

   /**
   * Get spare
   * @return spare
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSpare() {
    return spare;
  }


  public void setSpare(Integer spare) {
    this.spare = spare;
  }


  public PositionReport raim(Boolean raim) {
    
    this.raim = raim;
    return this;
  }

   /**
   * Get raim
   * @return raim
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getRaim() {
    return raim;
  }


  public void setRaim(Boolean raim) {
    this.raim = raim;
  }


  public PositionReport communicationState(Integer communicationState) {
    
    this.communicationState = communicationState;
    return this;
  }

   /**
   * Get communicationState
   * @return communicationState
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getCommunicationState() {
    return communicationState;
  }


  public void setCommunicationState(Integer communicationState) {
    this.communicationState = communicationState;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositionReport positionReport = (PositionReport) o;
    return Objects.equals(this.messageID, positionReport.messageID) &&
        Objects.equals(this.repeatIndicator, positionReport.repeatIndicator) &&
        Objects.equals(this.userID, positionReport.userID) &&
        Objects.equals(this.valid, positionReport.valid) &&
        Objects.equals(this.navigationalStatus, positionReport.navigationalStatus) &&
        Objects.equals(this.rateOfTurn, positionReport.rateOfTurn) &&
        Objects.equals(this.sog, positionReport.sog) &&
        Objects.equals(this.positionAccuracy, positionReport.positionAccuracy) &&
        Objects.equals(this.longitude, positionReport.longitude) &&
        Objects.equals(this.latitude, positionReport.latitude) &&
        Objects.equals(this.cog, positionReport.cog) &&
        Objects.equals(this.trueHeading, positionReport.trueHeading) &&
        Objects.equals(this.timestamp, positionReport.timestamp) &&
        Objects.equals(this.specialManoeuvreIndicator, positionReport.specialManoeuvreIndicator) &&
        Objects.equals(this.spare, positionReport.spare) &&
        Objects.equals(this.raim, positionReport.raim) &&
        Objects.equals(this.communicationState, positionReport.communicationState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageID, repeatIndicator, userID, valid, navigationalStatus, rateOfTurn, sog, positionAccuracy, longitude, latitude, cog, trueHeading, timestamp, specialManoeuvreIndicator, spare, raim, communicationState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    NavigationalStatus ns = NavigationalStatus.get(getNavigationalStatus());
    sb.append("class PositionReport {\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(repeatIndicator)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    navigationalStatus: ").append(toIndentedString(navigationalStatus)).append("-").append(toIndentedString(ns)).append("\n");
    sb.append("    rateOfTurn: ").append(toIndentedString(rateOfTurn)).append("\n");
    sb.append("    sog: ").append(toIndentedString(sog)).append("\n");
    sb.append("    positionAccuracy: ").append(toIndentedString(positionAccuracy)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    cog: ").append(toIndentedString(cog)).append("\n");
    sb.append("    trueHeading: ").append(toIndentedString(trueHeading)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    specialManoeuvreIndicator: ").append(toIndentedString(specialManoeuvreIndicator)).append("\n");
    sb.append("    spare: ").append(toIndentedString(spare)).append("\n");
    sb.append("    raim: ").append(toIndentedString(raim)).append("\n");
    sb.append("    communicationState: ").append(toIndentedString(communicationState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("NavigationalStatus");
    openapiFields.add("RateOfTurn");
    openapiFields.add("Sog");
    openapiFields.add("PositionAccuracy");
    openapiFields.add("Longitude");
    openapiFields.add("Latitude");
    openapiFields.add("Cog");
    openapiFields.add("TrueHeading");
    openapiFields.add("Timestamp");
    openapiFields.add("SpecialManoeuvreIndicator");
    openapiFields.add("Spare");
    openapiFields.add("Raim");
    openapiFields.add("CommunicationState");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("NavigationalStatus");
    openapiRequiredFields.add("RateOfTurn");
    openapiRequiredFields.add("Sog");
    openapiRequiredFields.add("PositionAccuracy");
    openapiRequiredFields.add("Longitude");
    openapiRequiredFields.add("Latitude");
    openapiRequiredFields.add("Cog");
    openapiRequiredFields.add("TrueHeading");
    openapiRequiredFields.add("Timestamp");
    openapiRequiredFields.add("SpecialManoeuvreIndicator");
    openapiRequiredFields.add("Spare");
    openapiRequiredFields.add("Raim");
    openapiRequiredFields.add("CommunicationState");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PositionReport
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PositionReport.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PositionReport is not found in the empty JSON string", PositionReport.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PositionReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PositionReport` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PositionReport.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PositionReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PositionReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PositionReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PositionReport.class));

       return (TypeAdapter<T>) new TypeAdapter<PositionReport>() {
           @Override
           public void write(JsonWriter out, PositionReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PositionReport read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

  public static PositionReport fromJson(JSONObject jo) {
    PositionReport res = new PositionReport();
    // Extract individual fields from JSONObject
    try {
        res = res.messageID(jo.getInt(SERIALIZED_NAME_MESSAGE_I_D));
        res = res.repeatIndicator(jo.getInt(SERIALIZED_NAME_REPEAT_INDICATOR));
        res = res.userID(jo.getInt(SERIALIZED_NAME_USER_I_D));
        res = res.valid(jo.getBoolean(SERIALIZED_NAME_VALID));
        res = res.navigationalStatus(jo.getInt(SERIALIZED_NAME_NAVIGATIONAL_STATUS));
        res = res.rateOfTurn(jo.getInt(SERIALIZED_NAME_RATE_OF_TURN));
        res = res.sog(jo.getDouble(SERIALIZED_NAME_SOG));
        res = res.positionAccuracy(jo.getBoolean(SERIALIZED_NAME_POSITION_ACCURACY));
        res = res.longitude(jo.getDouble(SERIALIZED_NAME_LONGITUDE));
        res = res.latitude(jo.getDouble(SERIALIZED_NAME_LATITUDE));
//        Position position = getPosition(jo);
        res = res.cog(jo.getDouble(SERIALIZED_NAME_COG));
        res = res.trueHeading(jo.getInt(SERIALIZED_NAME_TRUE_HEADING));
        res = res.timestamp(jo.getInt(SERIALIZED_NAME_TIMESTAMP));
        res = res.specialManoeuvreIndicator(jo.getInt(SERIALIZED_NAME_SPECIAL_MANOEUVRE_INDICATOR));
      // XXX spare 
        res = res.raim(jo.getBoolean(SERIALIZED_NAME_RAIM));
        res = res.communicationState(jo.getInt(SERIALIZED_NAME_COMMUNICATION_STATE));
      System.out.println(res);
    } catch (JSONException e) {
//        logger.error("Error creating ShipStaticData", e);
    }
    return res;
  }

 /**
  * Create an instance of PositionReport given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PositionReport
  * @throws IOException if the JSON string is invalid with respect to PositionReport
  */
//  public static PositionReport fromJson(String jsonString) throws IOException {
//    return JSON.getGson().fromJson(jsonString, PositionReport.class);
//  }

 /**
  * Convert an instance of PositionReport to an JSON string
  *
  * @return JSON string
  */
//  public String toJson() {
//    return JSON.getGson().toJson(this);
//  }
}

