/*
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.homebeaver.aismodel;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

//import org.openapitools.client.JSON;

/**
 * AIS message 24 - Class B "CS" static data, 
 * Additional data assigned to an MMSI Part A: Name Part B: Static Data
 * <p>
 * Static data report as defined by ITU-R M.1371-4
 */
/*
M.1371-4 :
3.22 Message 24: Static data report
Message 24 Part A and Part B may be used by any AIS station to associate a MMSI with a name.
Message 24 Part A and Part B should be used by Class B "CS" shipborne mobile equipment. 
	The message consists of two parts.
Message 24B should be transmitted within 1 min following Message 24A.
In case of an interrogation for a Class B "CS" (Carrier sense) on a Message 24, 
the response should include Part A and Part B.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T20:57:25.293422-07:00[America/Vancouver]")
public class StaticDataReport extends AisMessage {

  public static final String SERIALIZED_NAME_RESERVED = "Reserved";
  @SerializedName(SERIALIZED_NAME_RESERVED)
  private Integer reserved;

  /**
   * Identifier for the message part number; always 0 (false) for Part A
   * TRUE => for Part B
   */
  public static final String SERIALIZED_NAME_PART_NUMBER = "PartNumber";
  @SerializedName(SERIALIZED_NAME_PART_NUMBER)
  private Boolean partNumber;

  public static final String SERIALIZED_NAME_REPORT_A = "ReportA";
  @SerializedName(SERIALIZED_NAME_REPORT_A)
  private StaticDataReportReportA reportA;

  public static final String SERIALIZED_NAME_REPORT_B = "ReportB";
  @SerializedName(SERIALIZED_NAME_REPORT_B)
  private StaticDataReportReportB reportB;

	public StaticDataReport() {
		super();
	}

  public StaticDataReport reserved(Integer reserved) {
    this.reserved = reserved;
    return this;
  }

   /**
   * Get reserved
   * @return reserved
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getReserved() {
    return reserved;
  }


  public void setReserved(Integer reserved) {
    this.reserved = reserved;
  }


  public StaticDataReport partNumber(Boolean partNumber) {

    this.partNumber = partNumber;
    return this;
  }

   /**
   * Get partNumber
   * @return partNumber
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getPartNumber() {
    return partNumber;
  }


  public void setPartNumber(Boolean partNumber) {
    this.partNumber = partNumber;
  }


  public StaticDataReport reportA(StaticDataReportReportA reportA) {

    this.reportA = reportA;
    return this;
  }

   /**
   * Get reportA
   * @return reportA
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StaticDataReportReportA getReportA() {
    return reportA;
  }


  public void setReportA(StaticDataReportReportA reportA) {
    this.reportA = reportA;
  }


  public StaticDataReport reportB(StaticDataReportReportB reportB) {

    this.reportB = reportB;
    return this;
  }

   /**
   * Get reportB
   * @return reportB
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StaticDataReportReportB getReportB() {
    return reportB;
  }


  public void setReportB(StaticDataReportReportB reportB) {
    this.reportB = reportB;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticDataReport staticDataReport = (StaticDataReport) o;
    return Objects.equals(getMessageID(), staticDataReport.getMessageID()) &&
           Objects.equals(getRepeatIndicator(), staticDataReport.getRepeatIndicator()) &&
           Objects.equals(getUserID(), staticDataReport.getUserID()) &&
           Objects.equals(getValid(), staticDataReport.getValid()) &&
        Objects.equals(this.reserved, staticDataReport.reserved) &&
        Objects.equals(this.partNumber, staticDataReport.partNumber) &&
        Objects.equals(this.reportA, staticDataReport.reportA) &&
        Objects.equals(this.reportB, staticDataReport.reportB);
  }

	@Override
	public int hashCode() {
		return Objects.hash(getMessageID(), getRepeatIndicator(), getUserID(), getValid(), 
		reserved, partNumber, reportA, reportB);
	}

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticDataReport {\n");
    sb.append("    messageID: ").append(toIndentedString(getMessageID())).append("\n");
    sb.append("    repeatIndicator: ").append(toIndentedString(getRepeatIndicator())).append("\n");
    sb.append("    userID: ").append(toIndentedString(getUserID())).append("\n");
    sb.append("    valid: ").append(toIndentedString(getValid())).append("\n");
    sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
    sb.append("    partNumber: ").append(toIndentedString(partNumber)).append("\n");
    sb.append("    reportA: ").append(toIndentedString(reportA)).append("\n");
    sb.append("    reportB: ").append(toIndentedString(reportB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MessageID");
    openapiFields.add("RepeatIndicator");
    openapiFields.add("UserID");
    openapiFields.add("Valid");
    openapiFields.add("Reserved");
    openapiFields.add("PartNumber");
    openapiFields.add("ReportA");
    openapiFields.add("ReportB");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("MessageID");
    openapiRequiredFields.add("RepeatIndicator");
    openapiRequiredFields.add("UserID");
    openapiRequiredFields.add("Valid");
    openapiRequiredFields.add("Reserved");
    openapiRequiredFields.add("PartNumber");
    openapiRequiredFields.add("ReportA");
    openapiRequiredFields.add("ReportB");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to StaticDataReport
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (StaticDataReport.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in StaticDataReport is not found in the empty JSON string", StaticDataReport.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!StaticDataReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StaticDataReport` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StaticDataReport.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `ReportA`
      if (jsonObj.getAsJsonObject("ReportA") != null) {
        StaticDataReportReportA.validateJsonObject(jsonObj.getAsJsonObject("ReportA"));
      }
      // validate the optional field `ReportB`
      if (jsonObj.getAsJsonObject("ReportB") != null) {
        StaticDataReportReportB.validateJsonObject(jsonObj.getAsJsonObject("ReportB"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StaticDataReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StaticDataReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StaticDataReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StaticDataReport.class));

       return (TypeAdapter<T>) new TypeAdapter<StaticDataReport>() {
           @Override
           public void write(JsonWriter out, StaticDataReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StaticDataReport read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

/*
{"Message":{"StaticDataReport":{"MessageID":24,"PartNumber":false,"RepeatIndicator":0
,"ReportA":{"Name":"INTREPID","Valid":true}
,"ReportB":{"CallSign":"","Dimension":{"A":0,"B":0,"C":0,"D":0},"FixType":0,"ShipType":0,"Spare":0,"Valid":false,"VenderIDModel":0,"VenderIDSerial":0,"VendorIDName":""}
,"Reserved":0,"UserID":319153700,"Valid":true}}
,"MessageType":"StaticDataReport","MetaData":{"MMSI":319153700,"MMSI_String":319153700,"ShipName":"INTREPID","latitude":39.56529,"longitude":2.633321666666667,"time_utc":"2025-10-30 20:13:45.141364981 +0000 UTC"}}
 */
	public static StaticDataReport fromJson(JSONObject jo) {
		AisMessage res = new StaticDataReport();
		StaticDataReport sdr = null;
		// Extract individual fields from JSONObject
		try {
			res = res.messageID(jo.getInt(SERIALIZED_NAME_MESSAGE_I_D));
			res = res.repeatIndicator(jo.getInt(SERIALIZED_NAME_REPEAT_INDICATOR));
			res = res.userID(jo.getInt(SERIALIZED_NAME_USER_I_D));
			res = res.valid(jo.getBoolean(SERIALIZED_NAME_VALID));
			sdr = (StaticDataReport) res;
			sdr = sdr.partNumber(jo.getBoolean(SERIALIZED_NAME_PART_NUMBER));
			JSONObject ra = jo.getJSONObject(SERIALIZED_NAME_REPORT_A);
			sdr = sdr.reportA(StaticDataReportReportA.fromJson(ra));
			JSONObject rb = jo.getJSONObject(SERIALIZED_NAME_REPORT_B);
			sdr = sdr.reportB(StaticDataReportReportB.fromJson(rb));
			sdr = sdr.reserved(jo.getInt(SERIALIZED_NAME_RESERVED));
//			System.out.println(sdr);
		} catch (JSONException e) {
	//        logger.error("Error creating StaticDataReport", e);
			System.out.println("Error creating StaticDataReport " + e);
		}
		return sdr;
	}

}
